### ISSUE TITLE
Update build pipeline to be more efficient

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-aws#116]
We'd like to reduce the time between pushing changes and builds finishing.  Would be nice to have the process auto-restart the associated ECS task

**Comment by mmacduff** [comment]
Items to be considered.
multi-stage build for apbs/pdb2pqr and separate stage for job_control
detect file changes to determine what to rebuild
kill affected running tasks so they restart with new image

this will mostly be in the buildspec and Dockerfiles

**Comment by mmacduff** [comment]
Further optimizations could be considered but the update and build script improves things sufficiently for now.
