### ISSUE TITLE
Add storage to job execution instance

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-aws#119]
Due to nature of Fargate, jobs currently write data to memory.  In order to not cut into our memory limits, we'd need to add more storage either by way of ephemeral storage or additional RAM

**Comment by mmacduff** [comment]
Looking at this.  Ec2 already include 30g of local storage.  and Fargate includes 20G by default.
Adding environment variable to task definitions of "JOB_PATH=/var/tmp" would use this space.
Or just change the default in job_control.py would be more transparent.
