### ISSUE TITLE
Missing DX file

### ISSUE THREAD

**Issue by MinghaoChen10** [Electrostatics/apbs-aws#134]
Dear developer,

I'm using APBS from the online server but I couldn't find the .dx file on the output file page.
Instead, I got a large file (~15GB) named "core.17".

My jobID is "ele2veza8n_20211108". Could you please take a look at it?
Thank you very much!

Minghao

**Comment by sobolevnrm** [comment]
Hi @MinghaoChen10 -- would you be willing to share the PDB file you used, either by uploading here as a ZIP or with a `.txt` extension or by emailing it to me at nathanandrewbaker@gmail.com?  Thank you.
