### ISSUE TITLE
Upgrade PDB2PQR

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/apbs-aws#146]
Please upgrade the web server version of PDB2PQR to [v3.5.0](https://github.com/Electrostatics/pdb2pqr/releases/tag/v3.5.0).

Is it possible to automate upgrades when new versions are released?

**Comment by mmacduff** [comment]
This has been updated on test and production. 
We can look at a trigger to detect a new tag on that repo.   We can discuss if that should automatically update the test or prod sites.

**Comment by intendo** [comment]
I started a [discussion](https://github.com/Electrostatics/apbs-aws/discussions/150) about this.
