### ISSUE TITLE
Create Job Service to interpret job submissions and submit to queue

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-aws#2]
**Input**:
* S3 event with submitted job information

**Output**:
* Status file for job: upload to S3
* Interpreted job information; push to SQS

**Comment by intendo** [comment]
@Eo300 
Is this implemented already in https://github.com/Electrostatics/apbs-aws/blob/main/src/lambda_services/job_service/job_service.py?

**Comment by Eo300** [comment]
This functionality is implemented and the [main](https://github.com/Electrostatics/apbs-aws/tree/main) branch is now ahead.  Additional changes needed can be handled on a per-issue basis

This issue's safe to close and the associated branch should be safe to delete
