### ISSUE TITLE
Create Docker image for running APBS

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-aws#4]
Write the Dockerfile for an image that executes APBS jobs\

**Container will need to:**
1. Retrieve job information from SQS
2. Download input files from S3
3. Run APBS
4. Upload output files and final status to S3

**Comment by intendo** [comment]
@Eo300
Is this done as part of https://github.com/Electrostatics/apbs-aws/blob/main/src/docker/Dockerfile?
Or is it:
- out of date and no longer needed?
- new for apbs3.1?

**Comment by Eo300** [comment]
The target functionality for both this issue and #5 was achieved through the following:
* https://github.com/Electrostatics/apbs-aws/blob/main/src/docker/Dockerfile
* https://github.com/Electrostatics/apbs-aws/blob/main/src/docker/job_control.py

As such, both issues should be safe to close
