### ISSUE TITLE
Fix job_service relative import issue

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-aws#45]
Relative import causes errors when deployed to lambda

See: https://github.com/Electrostatics/apbs-aws/blob/aeaccd429c5faffaae1fd3c9465cdf69d0b23d84/lambda_services/job_service/job_service.py#L7

**Comment by intendo** [comment]
I found https://gist.github.com/gene1wood/06a64ba80cf3fe886053f0ca6d375bc0 which might help us figure this out as we restructure the directories.

**Comment by mmacduff** [comment]
Deployed with the code folder 'job_service/....' and adding __init__.py resolved this issue.
Had to also update the ansible config to match the paths
