### ISSUE TITLE
Create Docker image for running PDB2PQR

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-aws#5]
Write the Dockerfile for an image that executes PDB2PQR jobs

**Container will need to:**
1. Retrieve job information from SQS
2. Download input files from S3, or Protein Data Bank if needed
3. Run PDB2PQR
4. Upload output files and final status to S3

**Comment by intendo** [comment]
@Eo300 
Is this done as part of https://github.com/Electrostatics/apbs-aws/blob/main/src/docker/Dockerfile?
Or is it:
- out of date and no longer needed?
- new for pdb2pqr30?

**Comment by Eo300** [comment]
This one's out-of-date and no longer needed; see https://github.com/Electrostatics/apbs-aws/issues/4#issuecomment-809767444
