### ISSUE TITLE
Add job stats to job_control.py

### ISSUE THREAD

**Issue by Eo300** [Electrostatics/apbs-aws#53]
See:
https://github.com/Electrostatics/apbs-aws/blob/main/src/docker/job_control.py#L127

**Comment by intendo** [comment]
The code is already written in other places, but I can add it to job_control.py so there is no library dependencies.
We can use my JobStats, resource.getrusage to get memory stats for each job.
We can use get_execution_time (subtract {jobtype}_start_time from {jobtype}_end_time) to find out how long a job runs
We can get disk storage by using get_storage_usage (stat all files in output directory).
I can add this code to job_control and have it create a JSON object in {jobtype}-stats.json.
