### ISSUE TITLE
Add git commit to status file

### ISSUE THREAD

**Issue by mmacduff** [Electrostatics/apbs-aws#56]
https://github.com/Electrostatics/apbs-aws/blob/0f1038e2bc56d75f6ee34f42df4abf6d31ea9d37/src/docker/job_control.py#L271

Add a git commit version to the status file.
Need to add CODEBUILD_RESOLVED_SOURCE_VERSION to a file during buildspec.yml (or possibly Dockerfile).

**Comment by intendo** [comment]
Purpose: Each job has a list of versions of software (APBS, PDB2PQR, job_control?, Python?) used to generate the data
Created/Maintained: During CodePipeline build step and create/update new file
Job Services would look for S3://web/$info/versions.json file and include it in the job_status.json file
